module.exports = [
  {
    files: ["js/*.js"],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "script",
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        location: "readonly",
        history: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        fetch: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        performance: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        HTMLElement: "readonly",
        Element: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        ResizeObserver: "readonly",
        AbortController: "readonly",
        FormData: "readonly",
        Blob: "readonly",
        FileReader: "readonly",
        Image: "readonly",
        Audio: "readonly",
        MediaQueryList: "readonly",
        matchMedia: "readonly",
        getComputedStyle: "readonly",
        structuredClone: "readonly",
        queueMicrotask: "readonly",
        reportError: "readonly",
        crypto: "readonly",
        indexedDB: "readonly",
        caches: "readonly",
        self: "readonly",
        globalThis: "readonly",
        // Web APIs
        ServiceWorkerRegistration: "readonly",
        Notification: "readonly",
        // Common patterns in this project
        HARNESSLogger: "readonly",
      },
    },
  },
];
