#!/usr/bin/env python3
"""
Fix navigation and transparency issues across all HTML files
"""
import re
import os
from pathlib import Path

def fix_html_file(filepath):
    """Fix navigation and transparency issues in a single HTML file"""
    print(f"Processing: {filepath}")
    
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    original_content = content
    
    # Remove the duplicate static <nav> element (keep only the dynamically loaded one)
    # Look for <nav> tags that are NOT part of the script-generated navigation
    # Pattern to match static nav elements in the body
    nav_pattern = r'<!-- Navigation & Footer loaded automatically.*?-->\s*<!-- Navigation -->\s*<nav>.*?</nav>'
    content = re.sub(nav_pattern, '<!-- Navigation loaded dynamically by script -->', content, flags=re.DOTALL)
    
    # Also remove any standalone <nav> elements that might be in the body
    # This is more aggressive but necessary for cleanup
    body_nav_pattern = r'<body[^>]*>.*?(<nav(?:\s+class="[^"]*")?>\s*<div class="container">.*?</nav>)'
    matches = re.finditer(body_nav_pattern, content, re.DOTALL)
    
    for match in matches:
        nav_content = match.group(1)
        # Only remove if it's a static nav (not generated by script)
        if 'harness-universal-nav' not in nav_content:
            content = content.replace(nav_content, '<!-- Navigation loaded dynamically -->')
    
    # Fix inline styles on logos that might override transparency
    # Remove background styles from img tags with logo in src
    content = re.sub(
        r'(<img[^>]*src="[^"]*logo[^"]*"[^>]*)\s*style="[^"]*"',
        r'\1',
        content,
        flags=re.IGNORECASE
    )
    
    # Ensure the transparent-headers.css is loaded
    if 'transparent-headers.css' not in content:
        # Add it after the first <link rel="stylesheet"
        content = re.sub(
            r'(<link rel="stylesheet"[^>]*>)',
            r'\1\n    <link rel="stylesheet" href="css/transparent-headers.css">',
            content,
            count=1
        )
    
    # Fix any hardcoded background colors on nav elements
    content = re.sub(
        r'(<nav[^>]*)\s*style="[^"]*background[^"]*"',
        r'\1',
        content,
        flags=re.IGNORECASE
    )
    
    # Ensure nav elements have proper classes for transparency
    content = re.sub(
        r'<nav\s*>',
        '<nav class="harness-nav">',
        content
    )
    
    # Only write if changes were made
    if content != original_content:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"  ✓ Fixed: {filepath}")
        return True
    else:
        print(f"  - No changes needed: {filepath}")
        return False

def main():
    """Process all HTML files in the project"""
    project_root = Path('/home/ubuntu/theharnessproject')
    html_files = list(project_root.glob('*.html'))
    
    print(f"Found {len(html_files)} HTML files to process\n")
    
    fixed_count = 0
    for html_file in html_files:
        if fix_html_file(html_file):
            fixed_count += 1
    
    print(f"\n{'='*60}")
    print(f"Processing complete!")
    print(f"Fixed {fixed_count} out of {len(html_files)} files")
    print(f"{'='*60}")

if __name__ == '__main__':
    main()
